### PR TITLE
ComNav receiver support

### PR DESCRIPTION
**Pull request by Allidylls**
Add support for ComNav receivers.

### CODE REVIEW

**Comment by Matioupi** [comment]
Hello, what are the differences between ComNav and Novatel OEM6 raw data format ?
As far as I can see, RANGECMPB, IONUTCB, RAWEPHEMB and GLORAWEPHEMB have the same binary format (but I may have missed some subtlties).

**Comment by tomojitakasu** [comment]
Please contact ComNav.

**Comment by Matioupi** [comment]
I hope my question was not inapropriate.
I own two K501G boards and I'm using them with RTKLIB right now.
I'm using the OEM6 input format and it seems to work perfectly.
I can see that SBAS/WAAS ephemerids frames are missing in COMNAV firmware reference manuel (rev 1.3) compared to OEM6 but for the main GPS/GLONASS messages, it seems to share the same format.

**Comment by Allidylls** [comment]
Yes, ComNav is a new developing maker of precise GNSS receiver. The most NovAtel-compatible data frame is used to fit the market already exists, but as the first precise applier of  Beidou system, ComNav defines different satellites ids of the BDS. So, there is no problem with NovAtel of GPS and GLONASS.

**Pull request closed without merging**
