### PR TITLE
CMR/CMR+ protocol support for RTKLIB

### PR DESCRIPTION
**Pull request by astrodanco**
CMR message types 0, 1 and 2 are implemented.
CMR message type 3 (GLONASS) is implemented.
CMR message type 4, high speed CMR (5, 10, 20 Hz), is implemented.
CMR+ message types 1, 2 and 3 are implemented.
An RT17 code refactor with accumulated bug fixes is included.
A link to an archive containing a set of time tagged data files will be sent to you via email later this evening.

Your code review is appreciated. Your critical examination of why it doesn't get past FLOAT whereas RCTM3 quickly gets a FIX with AR skyrocketing to 999.9 in the same testing circumstances is also appreciated. Please feel free to make helpful corrections as needed.

Things that still need to be done:
1. rtkrcv's display of RTCM message counts needs to be conditioned on CMR format as was done for rtknavi.
2. Possible minor CMR aware UI tweaks - where it matters.
3. I doubtlessly missed a few things here and there. It happens.

### CODE REVIEW

**Comment by mbbee** [comment]
Hi,
i would like convert CMR+ to RTCM3 with str2str
command:
str2str -t 3 -in ntrip://[user[:passwd]@]addr[:port][/mntpnt]#cmr  -out tcpsvr://:2101#rtcm3 ...
The login to the Trimble AgGPS 542 GNSS receiver works.

At the output side i only get nothing or garbage ... 

Which output messages and other parameter do i have to define?

THX!

**Comment by astrodanco** [comment]
> i would like convert CMR+ to RTCM3 with str2str 

 

Please read reference #1:

 

https://gpsd.googlecode.com/files/Trimble-CMR.pdf

 

And it should make sense to you why you cannot do that.

 

- Dan

**Comment by astrodanco** [comment]
Takasu san, you should have received the test data via email. If you didn't receive it, it is also available for download as a ZIP archive at the following link:

https://1drv.ms/u/s!AqqNKhkHjDbyg06eYBRSg6w5uYq7

**Comment by tomojitakasu** [comment]
Thanks for providing CMR/CMR+ support for RTKLIB.

I had checked your code. Would you consider the modification of your codes as follows?

(1) The cmr.h should be integrated to cmr.c. It is to avoid complex dependency to header files.
(2) The struct rtcm_t would like to be only for RTCM messages. So the info of cmr_t should be included in raw_t.
(3) The raw_t is already messy and complex by importing many receiver's info. So I would like to reconstruct raw_t to separate receiver independent part and dependent one. The receiver-dependent part simply consts of a stream format type and a pointer to receiver dependent struct like:
typedef struct {
   gtime_t time;
   ...
   int strfmt; /* stream format type */
   void *rcv_data; /* pointer to receiver-dependent data */
} raw_t;
The cmr_t and rt17_t should be pointed by the rcv_data;
(4) For (3), the functions of init_rrr() and free_rrr() (rrr is the stream format like "bnx") called by init_raw() and free_raw() should be added to each receiver driver.

**Comment by astrodanco** [comment]
Takasu san, a question for you. The time in the rtcm structure is GPS time. What is the time in the raw structure? It doesn't appear to be GPS time.

**Comment by astrodanco** [comment]
During the merge you made a typo in rtksvr.c as follows:

This (incorrect):

        /* update cmr rover observations cache */
        if (svr->format[0]==STRFMT_CMR&svr->format[1]==STRFMT_CMR&&
            index==0&&ret==1) {
            update_cmr(&svr->raw[1],svr,obs);
        }

Should be this (correct):

        /* update cmr rover observations cache */
        if ((svr->format[1]==STRFMT_CMR)&&(index==0)&&(ret==1))
            update_cmr(&svr->raw[1], svr, obs);

**Comment by tomojitakasu** [comment]
Thanks. It's fixed in rtklib 2.4.3 b15.

**Pull request closed without merging**
