### PR TITLE
add Qt port GUI applications

### PR DESCRIPTION
**Pull request by JensReimann**
this repository includes:
- all GUI applications ported to Qt (tested on Windows and Linux using Qt Creator and GCC)
- latest Septentrio receiver support
- Windows support of RTKLib coonverted to "ANSI strings only" to make GCC happy (Needs to be sorted)
- few renames for API functions (compress(), crc??()) to solve naming conflicts with other libraries

### CODE REVIEW

**Comment by jlblancoc** [comment]
This is great, @JensReimann , thank you so much!

**Comment by DavidKelleySCSC** [comment]
**All I can say is WOW!**
I had to remove the sub project rnx2rtkp to get it to build (did you forget something in your collected file sets?) and here I am looking at what appears a translation of RTKLIB into Qt  (I am running 5.5 here).  Looks like this was translated using an automated tool, how was it done? I want to recall there was at tool that took Borland's GUI code and transformed it into Qt4, one of our staff used that a while back but said it was no longer supported, but this code looks cleaner.   
I see tons of small code GUI issues to correct, mostly due to the presumed auto translation nature, but do not take that as a negative.  I would love to see RTKplot work live, but so far only with a file set.  No apparent ini file saving. Some Message display and decoding in the RTK monitor dialogs display blank (it clearly does decode, just not shown).  Have mostly run simple filters so far, got RTK to fix in the normal way with our test stations, but (oddly) was unable to get a fix when using the same station as the rover and base (this should fix instantly). So me, the various tools are not connecting to each other have to run each one at a time.  All just first impressions as I tinker with it. 

I think this is a great bit of work, and hope that Takasu san will too.  As an unabashed Qt user/lover, I would love the see the project move in this directions.  Again wow!  So what is your plan for next steps or more?

**Comment by JensReimann** [comment]
What to do next? 
- fix bugs and make it stable (Bug reports and patches are welcome. I just cannot test every code path.)
- fix remaining issues in RTKlib with Takasu (e.g. UNICODE support, naming conflicts)
- make code more Qt-ish - at least in some places

and in the long run
- add some more plotting types to rtkplot_qt (i.e. atmosphere, ionosphere)
- any further ideas?

BTW: Only the GUI files where automatically translated. "Search & Replace" is also your friend :-)

**Comment by mr337** [comment]
Confused, what happen to this PR?

**Pull request closed without merging**
